export enum SafetySignatureStatusCode {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  HIDDEN = 'HIDDEN',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
  RESTRICTED = 'RESTRICTED',
  PRIVATE = 'PRIVATE',
  EXPIRED = 'EXPIRED',
}
