spring:
  security:
    oauth2:
      client:
#        provider:
#          naver:
#          kakao:
        registration:
          google:
            client-id: 426612864149-09aicu22eao50v1vlraqvp8qu8lnjr91.apps.googleusercontent.com
#          kakao:
#            client-name: kakao
#            authorization-grant-type: authorization_code
##            redirect-uri:
#            client-id: befbcc3b228e5e70dcb91db6452622aa
##            client-secret:
##            client-authentication-method: client_secret_post
#            scope:
#              - profile_nickname
#              - account_email
#              - profile_image
access-token:
  secret-key: ENC(M2o/g3PSJwzjB3wyuEVJx38we5yXOVN5gqBpa0gp6IAnq+NXS4FxxvvWItON8PzkSKgmLhKIk1A=)
  expire-length: 3600000

refresh-token:
  expire-length: 1209600000

kakao-admin-key: afddce59b15ab720506c267076afe3b5