import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import PageChangeMiddleware from '@/middleware/pageChangeMiddleware'
import ReactQueryProviders from '@/hooks/useReactQuery'
import Loading from '@/components/common/Loading'
import Footer from '@/components/layout/Footer'
import Header from '@/components/layout/Header'
import MainBody from '@/components/layout/MainBody'
import StyledComponentsRegistry from '@/components/layout/StyledComponentsRegistry'
import queryClient from './queryClient'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: '안전문서 전자결재 관리자 사이트',
  description: 'Generated by ohjinseo',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StyledComponentsRegistry>
          <PageChangeMiddleware>
            <ReactQueryProviders>
              <Loading />
              <Header />
              <MainBody>{children}</MainBody>
              <Footer />
            </ReactQueryProviders>
          </PageChangeMiddleware>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
