server:
  port: 8080
  servlet:
    context-path: /services/backend

spring:
  application:
    name: safety_signature_back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(j5u3O8qDJlFBy5+lnH1LSFZYg26UMcMoOOaOtKO/2bz1Y9rWQxPfp4JkoKLOpONczOUoIhO6qYM=)
    username: ENC(J1ub9wjNqELFNx9wQTuW9NI0WQ1orwMB)
    password: ENC(RsASFvqSB5ZBFJUZmg9CLOufiyacW1lz) # ?? ???? ??? ??

  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update        # DB 초기화 전략 (none, create, create-drop, update, validate)
    open-in-view: false
    properties:
      hibernate:
        #        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true      #
        show_sql: true        #
    show-sql: true

  config:
    import:
      classpath:/private/application-security.yml
  sql:
    init:
      platform: postgres

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
logging:
  level:
    root: info # debug info
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO
      sqlonly: OFF

springdoc:
  swagger-ui:
    path: /swagger/docs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

client:
  minio:
    endpoint: ENC(6cnW1pkH/MvlIlkxOmcl7pwslbWgoPCBLTQ3fcovvP/kZd7bjTv1Ow==)
    accessKey: ENC(yoMcN5drulN6HICqepLBMenc79uE2UIPDPWG1sECGKQ=)
    secretKey: ENC(qMEbzUHC1CJfVs/7YI9S5Dg5friNBL/eQLsW+xyLHRWDzaSljNlXHq/xFAfprNp3jYvvCLd8kfE=)
    bucket: ENC(PsWwjTKdkxsrXBMC3rafHBfjyAKpQIMc)
    bucketImage: ENC(45PYxGPA09gS4BRi02R9HlRRAmz+umZ+OHcqjPWx3W8=)
